# https://circleci.com/docs/2.0/

version: 2
workflows:
  version: 2

  ci:
    jobs:
      # Platforms
      - "ubuntu-18.04"

jobs:
  ubuntu-18.04:
    docker:
      - image: "ubuntu:18.04"

    environment:
      # Add /root/.local/bin to PATH so that the upgraded stack is preferred.
      PATH: "/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    steps:
      - "checkout"

      - run:
          name: "Install Stack"
          command: |
            apt-get --quiet update
            apt-get --quiet --yes install netbase haskell-stack

      - restore_cache:
          name: "Restoring Stack installation cache"
          keys:
            - "v1-stack-installation"

      - run:
          name: "Upgrading Stack"
          command: |
            stack upgrade

      - save_cache:
          name: "Caching upgraded Stack installation"
          key: "v1-stack-installation"
          paths:
            - "/root/.local/bin/stack"

      - run:
          name: "Run Tests"
          command: |
            stack test
